# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_cityinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityId', models.CharField(max_length=32, verbose_name='城市id')),
                ('minTem', models.CharField(max_length=32, verbose_name='最低温度')),
                ('maxTem', models.CharField(max_length=32, verbose_name='最高温度')),
                ('wind', models.CharField(max_length=32, verbose_name='风向')),
                ('todayWea', models.CharField(max_length=32, verbose_name='今天天气')),
                ('tomWea', models.CharField(max_length=32, verbose_name='明天天气')),
                ('afterTomWea', models.CharField(max_length=32, verbose_name='后天天气')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
        ),
    ]
