# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20170928_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='temdate',
        ),
    ]
