# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_remove_weatherinfo_temdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='wind',
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='temdate',
            field=models.DateField(default=datetime.datetime(2017, 9, 28, 8, 24, 38, 715187, tzinfo=utc), verbose_name='日期'),
        ),
    ]
