# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_auto_20170928_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='wind',
            field=models.CharField(default='', max_length=32, verbose_name='风向'),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='temdate',
            field=models.DateField(default=datetime.datetime(2017, 9, 28, 8, 32, 52, 143261, tzinfo=utc), verbose_name='日期'),
        ),
    ]
